apk_analyzer/config/routes.rb
Rails.application.routes.draw do
  get 'aosp/index'
  get 'aosp/update'
  get 'aosp_gas/index'
  get 'aosp_gas/update'
  get 'polestar/index'
  get 'polestar/update'
  get 'apps/index'
  get 'apps/update'
  get 'apps/clean'
  get 'overview/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :apps

  root 'apps#index'
end

apk_analyzer/app/controllers/polestar_controller.rb
class PolestarController < ApplicationController
  helper_method :numServices
  helper_method :numReceivers
  helper_method :numProviders

  def update
    files = Dir.glob("#{Rails.root}/manifests/polestar/*")
    @apps = Array.new

    files.each do |file|
      inputFile = File.read(file)
      doc = Nokogiri::XML(inputFile)
      slop = doc.slop!

      filename = File.basename(file)
      package = slop.manifest["package"]
      isApp = doc.xpath("//application").size
      hasActivity = doc.xpath("//activity").size,
      hasOverlay = doc.xpath("//overlay").size
      numServices = doc.xpath("//service").size
      numReceivers = doc.xpath("//receiver").size
      numProviders = doc.xpath("//provider").size
      usedPermissions = doc.xpath("//uses-permission/@android:name").size
      createdPermissions = doc.xpath("//permission").size
      bootCompleted = doc.xpath("//uses-permission[@android:name='android.permission.RECEIVE_BOOT_COMPLETED']").size
      persistent = doc.xpath("//application[@android:persistent='true']").size
      supplier = "AOSP"
      usedPermissionsList = ""
      createdPermissionsList = ""
      servicesList = ""
      receiversList = ""
      provdersList = ""

      doc.xpath("//uses-permission/@android:name").each do |node|
        usedPermissionsList += node.to_s + "
        "
      end

      doc.xpath("//permission/@android:name").each do |node|
        createdPermissionsList += node.to_s + "
        "
      end

      doc.xpath("//service/@android:name").each do |node|
        servicesList += node.to_s + "
        "
      end

      doc.xpath("//receiver/@android:name").each do |node|
        receiversList += node.to_s + "
        "
      end

      doc.xpath("//provider/@android:name").each do |node|
        provdersList += node.to_s + "
        "
      end

      App.new("project": "polestar","filename": filename, "package": package, "hasActivity": hasActivity, "hasRO": hasOverlay,
        "numOfReceivers": numReceivers, "numOfServices": numServices, "numOfProviders": numProviders,
        "createdPermissions": createdPermissions, "usedPermissions": usedPermissions,
        "bootCompleted": bootCompleted, "persistent": persistent, "hasApplication": isApp, "supplier": supplier,
        "usedPermissionsList": usedPermissionsList, "createdPermissionsList": createdPermissionsList,
        "servicesList": servicesList, "receiversList": receiversList, "provdersList": provdersList).save
    end
end

  def index
    @apps = App.where(project: "polestar")
  end

  def numServices(apps)
    numServices = 0
    apps.each do |app|
      numServices += app.servicesList.lines.count
      puts "app=" + app.package + ", has services:" + app.servicesList.size.to_s
    end
    puts "Found services:" + numServices.to_s
    @numServices = numServices
  end

  def numReceivers(apps)
    numReceivers = 0
    apps.each do |app|
      numReceivers += app.receiversList.lines.count
    end
    @numReceivers = numReceivers
  end

  def numProviders(apps)
    numProviders = 0
    apps.each do |app|
      numProviders += app.provdersList.lines.count
    end
    @numProviders = numProviders
  end

end

apk_analyzer/app/helpers/polestar_helper.rb
module PolestarHelper
end

apk_analyzer/app/views/polestar/index.html.erb
<h1><%= link_to 'Apps', apps_index_url %> | <%= link_to 'Polestar', polestar_index_url %> | <%= link_to 'AOSP (GAS)', aosp_gas_index_url %></h1>

<b>Number of apps:</b> <%= @apps.where(project: "polestar").size %>
<br>
<br>
<table id="example" class="table table-striped table-bordered" >
  <thead>
    <th id="package">Package</th>
    <th id="RO">RO</th>
    <th id="services">Services (<%= numServices(@apps.where(project: "polestar")) %>)</th>
    <th id="receivers">Receivers (<%= numReceivers(@apps.where(project: "polestar")) %>)</th>
    <th id="providers">Providers (<%= numProviders(@apps.where(project: "polestar")) %>)</th>
    <th id="permissions">used permissions</th>
    <th id="permissions">created permissions</th>
    <th id="BOOT_COMPLETED">BOOT_COMPLETED (<%= @apps.where(project: "polestar").where(bootCompleted: true).size %>)</th>
    <th id="persistent">Persistent (<%= @apps.where(project: "polestar").where(persistent: true).size %>)</th>
  </thead>
  <tbody>
   <% @apps.each do |app|%>
   <tr>
     <td><%= app.package %></td>
     <td><%= app.hasRO %></td>
     <td><%= app.numOfServices %></td>
     <td><%= app.numOfReceivers %></td>
     <td><%= app.numOfProviders %></td>
     <td><%= app.usedPermissions %></td>
     <td><%= app.createdPermissions %></td>
     <td><%= app.bootCompleted %></td>
     <td><%= app.persistent %></td>
   </tr>
   <% end %>
   </tbody>
</table>